import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}>

        {/* NAVBAR */}
        <nav className="h-20 w-full bg-black border-b border-white/10">
          <div className="max-w-7xl mx-auto h-full px-8 flex items-center justify-between">

            {/* Logo */}
            <div className="flex items-center gap-2">
              {/* White logo container – very tight */}
              <div className="bg-white rounded-md w-9 h-9 overflow-hidden flex items-center justify-center">
                <Image
                  src="/beyondlogo.png"
                  alt="Beyond Framez Logo"
                  width={60}
                  height={60}
                  className="object-cover w-16 h-16"
                />
              </div>

              {/* Brand name */}
              <span className="text-red-500 font-semibold text-lg">
                Beyond Framez
              </span>
            </div>


            {/* Links */}
            <div className="hidden md:flex items-center gap-8 text-sm text-gray-300">
              <a href="/" className="relative text-white">
                Home
                <span className="absolute -bottom-2 left-0 w-full h-[2px] bg-purple-500 rounded"></span>
              </a>
              <a href="/about" className="hover:text-white">About Us</a>
              <a href="/services" className="hover:text-white">Services</a>
              <a href="/portfolio" className="hover:text-white">Portfolio</a>
              <a href="/contact" className="hover:text-white">Contact Us</a>
            </div>

            {/* CTA */}
            <a
              href="/contact"
              className="bg-purple-600 hover:bg-purple-700 text-white text-sm px-5 py-2 rounded-full font-medium flex items-center gap-2"
            >
              Get a Quote →
            </a>

          </div>
        </nav>

        {/* PAGE CONTENT */}
        {children}

      </body>
    </html >
  );
}


